In [ ]:
import numpy as np

a= np.array(['ali','zofa','qureshi'])
b= np.array([2,3,4,5])
# print(a)
# print(b)
print(np.zeros(3))
print(np.ones(2))
print(np.empty(2))

seq= np.arange(2,22)
seq2= np.arange(2,22,2)
print("Range arrays",seq)
print("Range arrays",seq2)

In [ ]:
typearr=np.ones(4,dtype=np.float64)
print(typearr)

typearr=np.zeros(4,dtype=np.float64)
print(typearr)

In [ ]:
# sorting removien and adding in array
array= np.array([1,44,33,4,53])
sort= np.sort(array)
print(sort)
print(np.sort(np.array([44,33,3,22,34])))

print("sorting alphabets: ",np.sort(['d','ca','e','a']))

a1=np.array(['ab','ac','gcu','lahore'])
a2=np.array([2,44,33,23,456,12])
concat= np.concatenate((a1,a2))
print(concat)

print("elements in array",a1.shape[0])

In [ ]:
a1= np.array([[2,3,4,4,"hamza"],[2,33,4,3,"ali"]])
print(a1[1][4])
print(a1.shape)
print("even no:",np.arange(2,100+1,2))

In [ ]:
a2=np.array(["ali",3,43,23,11,6])
append=np.append(a2,'append')
print('added',append)

np.delete(a2,2)
print('removed',a2)



In [ ]:
#  finding dot product

w=100
x=20
b=40
dotp=np.dot(w,x)+b
print(dotp)

In [ ]:
#  Matrices in numpy

matrix= np.matrix([[3,1],[5,6]])
matrix2= np.matrix([[5,4],[52,4]])
# print(matrix,matrix2)

# print(np.sum(matrix))

prod=np.dot(matrix,matrix2)
print('Matrix Multi: ')
print(prod)


In [ ]:
#  Matrices in numpy
matrix= np.matrix([[3,1],[5,6]])
matrix2= np.matrix([[2,4],[1,2]])

In [ ]:
prod=np.dot(matrix,matrix2)
print('Matrix Multi: ')
print(prod)

In [19]:
# random arrays in numpy
import math
random= np.random.rand(4)
print(random)

random= np.random.rand(2,4)
print("2-d array with 2 rows and 4 elements:\n",random)

random= np.random.randint(20)
print("Random number:",random)

random= np.random.randint(255,size=5)
print("Random numbers:",random)

random= np.random.randint(0,50,size=10)
print("Random numbers:",random)

random= np.random.randn(10)
print("randn():",random)

[0.36590982 0.22980368 0.44045547 0.43198259]
2-d array with 2 rows and 4 elements:
 [[0.31667352 0.46637255 0.3517615  0.77110373]
 [0.57754721 0.42540084 0.35652088 0.45126708]]
Random number: 9
Random numbers: [ 70 175 173 228 165]
Random numbers: [ 4  2 15  4 40 21  4 22 22 42]
randn(): [-0.55834669 -1.37808032 -0.61385818  0.52420717  1.08386441 -0.00199594
 -1.4306745   1.47680548 -0.56757966 -0.88236055]


In [ ]:
#  sum of two matrix

sumMatrix= matrix+matrix2

print(sumMatrix)